import { NextRequest } from 'next/server';
import {
  authenticateApiRequest,
  requireScope,
  ApiScope,
  ApiRateLimitService,
  apiSuccess,
  apiErrorResponse,
  ApiError,
  ApiErrorCode,
  resolveRequestId,
} from '@/lib/api';
import { WebhookEndpointService } from '@/lib/webhooks/endpoint-service';
import { RecoverIQEventStore } from '@/lib/webhooks/event-store';
import { RecoverIQEventType } from '@/lib/webhooks/event-types';

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const requestId = resolveRequestId(req);

  try {
    const auth = await authenticateApiRequest(req);
    requireScope(auth.scopes, ApiScope.DEVELOPER_WRITE);
    const rateLimitHeaders = await ApiRateLimitService.assertRateLimit(auth.merchantId);

    const { id } = await params;
    const endpoint = await WebhookEndpointService.getEndpoint(id, auth.merchantId);
    if (!endpoint) {
      throw new ApiError(
        ApiErrorCode.RESOURCE_NOT_FOUND,
        `Webhook endpoint '${id}' not found for authenticated merchant.`,
        404,
        auth.requestId
      );
    }

    // Emit synthetic test event (test: true, livemode: false)
    const result = await RecoverIQEventStore.emitEvent({
      merchantId: auth.merchantId,
      type: RecoverIQEventType.WEBHOOK_TEST,
      aggregateType: 'system',
      aggregateId: `test_${Date.now()}`,
      payload: {
        message: 'This is a synthetic test event generated by RecoverIQ Developer Platform.',
        endpointId: id,
        livemode: false,
        test: true,
        timestamp: new Date().toISOString(),
      },
      test: true,
    });

    return apiSuccess(
      {
        message: 'Test event queued for delivery.',
        eventId: result.event.id,
        deliveryIds: result.deliveryIds,
      },
      auth.requestId,
      200,
      rateLimitHeaders
    );
  } catch (err: any) {
    const statusCode = err.statusCode || 400;
    const code = err.code || ApiErrorCode.INVALID_REQUEST;
    return apiErrorResponse(code, err.message, requestId, statusCode);
  }
}
