import { NextRequest, NextResponse } from 'next/server';
import { getTenantContext } from '@/lib/auth/tenant';
import { RecoverIQEventStore } from '@/lib/webhooks/event-store';
import { RecoverIQEventType } from '@/lib/webhooks/event-types';

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getTenantContext(req);
    const { id } = await params;

    const result = await RecoverIQEventStore.emitEvent({
      merchantId: session.merchantId,
      type: RecoverIQEventType.WEBHOOK_TEST,
      aggregateType: 'system',
      aggregateId: `test_${Date.now()}`,
      payload: {
        message: 'This is a synthetic test event generated by RecoverIQ Developer Platform.',
        endpointId: id,
        livemode: false,
        test: true,
        timestamp: new Date().toISOString(),
      },
      test: true,
    });

    return NextResponse.json({
      success: true,
      eventId: result.event.id,
      deliveryIds: result.deliveryIds,
    });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error?.message }, { status: 500 });
  }
}
